### ISSUE TITLE
Bad file descriptor

### ISSUE THREAD

**Issue by greek-stasia** [justfoxing/ghidra_bridge#64]
I have something that leverage some of the gui portions of ghidra and any button I click ( including the red x in the top right to close it) results in this error:

`_socket.error: [Errno 9] Bad file descriptor
Traceback (most recent call last):
  File "/home/stasia/ghidra_scripts/jfx_bridge/bridge.py", line 2092, in __call__
    return self._bridge_conn.remote_call(self._bridge_handle, *args, **kwargs)
  File "/home/stasia/ghidra_scripts/jfx_bridge/bridge.py", line 194, in wrapper
    return func(self, *args, **kwargs)
  File "/home/stasia/ghidra_scripts/jfx_bridge/bridge.py", line 1053, in remote_call
    return self.deserialize_from_dict(self.send_cmd(command_dict))
  File "/home/stasia/ghidra_scripts/jfx_bridge/bridge.py", line 207, in wrapper
    return_val = func(self, *args, **kwargs)
  File "/home/stasia/ghidra_scripts/jfx_bridge/bridge.py", line 959, in send_cmd
    write_size_and_data_to_socket(sock, data)
  File "/home/stasia/ghidra_scripts/jfx_bridge/bridge.py", line 311, in write_size_and_data_to_socket
    bytes_sent = sock.send(package[sent:])
  File "/home/stasia/ghidra_10.0.3_PUBLIC/Ghidra/Features/Python/data/jython-2.7.2/Lib/_socket.py", line 1387, in _dummy
    raise error(errno.EBADF, 'Bad file descriptor')
_socket.error: [Errno 9] Bad file descriptor`

I'm not exactly what to make of this. I'm not sure what IS the bad file it's referring to. 

Any insight would be appreciated!

**Comment by justfoxing** [comment]
At a guess, the socket error is because the ghidra-bridge client that was
doing something has closed its connection (probably because your script
finished), but has registered some sort of callback in ghidra that is being
triggered by GUI events. If that sounds about right, try making sure your
script removes those sorts of callbacks before it exits.

That's just a guess, though - if you could include your script, I could
give better advice.
